Example to show creation of tf.data.Dataset using csv

In [1]:
import pandas as pd
import tensorflow as tf

Read a csv file having three columns. We will name them to 'square_ft', 'house_type', and 'price'

In [2]:
csv_file = "./curated_data/train.csv"
csv_columns = ['square_ft', 'house_type', 'price']

In [3]:
dataset = tf.data.experimental.make_csv_dataset(csv_file, column_names=csv_columns, batch_size=8)

In [4]:
dataset

<PrefetchDataset shapes: OrderedDict([(square_ft, (8,)), (house_type, (8,)), (price, (8,))]), types: OrderedDict([(square_ft, tf.int32), (house_type, tf.string), (price, tf.float32)])>

In [5]:
for data in dataset.take(4):
    print(data)

OrderedDict([('square_ft', <tf.Tensor: shape=(8,), dtype=int32, numpy=array([1200, 2700, 2700, 2200, 1700, 1500, 1500, 2000])>), ('house_type', <tf.Tensor: shape=(8,), dtype=string, numpy=
array([b' apt', b' apt', b' house', b' apt', b' house', b' apt',
       b' house', b' house'], dtype=object)>), ('price', <tf.Tensor: shape=(8,), dtype=float32, numpy=array([0.6 , 1.35, 2.7 , 1.1 , 1.7 , 0.75, 1.5 , 2.  ], dtype=float32)>)])
OrderedDict([('square_ft', <tf.Tensor: shape=(8,), dtype=int32, numpy=array([1700, 2200, 1000, 1200, 2000, 1200, 2000, 1500])>), ('house_type', <tf.Tensor: shape=(8,), dtype=string, numpy=
array([b' apt', b' house', b' house', b' house', b' apt', b' apt',
       b' apt', b' apt'], dtype=object)>), ('price', <tf.Tensor: shape=(8,), dtype=float32, numpy=array([0.85, 2.2 , 1.  , 1.2 , 1.  , 0.6 , 1.  , 0.75], dtype=float32)>)])
OrderedDict([('square_ft', <tf.Tensor: shape=(8,), dtype=int32, numpy=array([2200, 2700, 2000, 1000, 1200, 2200, 1700, 1700])>), ('house_typ