In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(np.ndim(a))
print(a.shape)
print(a.shape[0])

[1 2 3 4]
1
(4,)
4


In [4]:
b=np.array([[1,2], [3,4],[5,6]])
print(b)
print(np.ndim(b))
print(b.shape)
print(b.shape[0])

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
3


In [7]:
''' matrix dot caluculation(ex.1) '''
A = np.array([[1,2], [3,4]])
print(A.shape)
B = np.array([[5,6], [7,8]])
print (B.shape)
print(np.dot(A, B))

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


In [11]:
''' matrix dot caluculation(ex.2)'''
C = np.array([[1,2,3], [4,5,6]])
print(C.shape[1])
D = np.array([[1,2], [3,4], [5,6]])
print(D.shape[0])
if C.shape[1] == D.shape[0]:
    print (np.dot(C, D))
else:
    print ("Can't caluculate np.dot()")

3
3
[[22 28]
 [49 64]]
