In [1]:
import numpy as np

In [2]:
A = np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

In [3]:
print(A)

[[1 4]
 [2 5]
 [3 6]]


In [4]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [8]:
B = A[::2]

In [9]:
print(B)

[[1 4]
 [3 6]]
